### PR TITLE
Platform/webgl/uum 15808/update brotli version

### PR DESCRIPTION
**Pull request by rachelmsimm**
This is branched off of unity_bro_exe and contains a merge of the latest brotli version 1.0.9 (master branch from https://github.com/google/brotli).

The plan is to merge these updates into unity_bro_exe, then merge:
unity_bro_exe --> unity

We shouldn't need the branch currently marked as master since it seems like its original intention was to be a copy of the master branch from Google's repo. We should rename unity to unity_master after the merge and explain that it is Google's master + customized add ons to use brotli with Unity in the README (and then probably delete the branch currently named master). We will also have to update the reference to the unity_bro_exe branch in https://github.com/Unity-Technologies/emscripten-builder

### CODE REVIEW

**Comment by rachelmsimm** [comment]
Going to get Jukka's username from him so I can add him to this PR as well

**Comment by rachelmsimm** [comment]
This outlines the testing I did for the change, I'm not sure its sufficient/gives us a fully accurate picture: https://docs.google.com/document/d/1Ek-BvzRRpqthtKwY2Jykqea7sR16Sjx1gdvtixeJ3IA/edit?usp=sharing

**Comment by juj** [comment]
Can you do the merge the other way around? We don't want to review all the code that came from upstream, there is too much of it.

So
1. Merge google/master to unity/master. This should be a fast-forward merge.
2. Propose a PR of unity/unity_bro_exe to unity/master, so that the PR will only show the code that we are layering on top of the new updated upstream.

I would do step 2 by rebasing unity/unity_bro_exe on top of google/master and then proposing it as a PR, or if the branch history in unity/unity_bro_exe is complex, by soft resetting unity/unity_bro_exe to its common ancestor commit with google/master, and then creating a new commit that has all of our changes in one commit, and then cherry-picking that commit on top of google/master.

Does not matter which way you'd go, but the important part is that we'll have a pull request that has all of our own code in it so that we can observe the changes that we are carrying against upstream google. I.e. the PR would show these changes: https://github.com/google/brotli/compare/master...Unity-Technologies:brotli:unity_bro_exe

**Comment by rachelmsimm** [comment]
@juj Thanks Jukka this is good feedback. I'll go ahead and do the steps as you suggested

**Comment by rachelmsimm** [comment]
Closing since we just want to rebase unity_bro_exe on top of master

**Pull request closed without merging**
